COUNTRY = None

COUNTRY_CODE = None
COUNTRY_SLANGS = None

COUNTRY_LONG = None
COUNTRY_LAT = None

COUNTRY_LOCATION_SLANGS = None
COUNTRY_USER_DESCRIPTION_SLANGS = None

HASHTAGS_COUNTRY_FILTERS = None

KNOWN_COUNTRY_TWITTER_USERNAMES = []

KNOWN_USERNAMES_COUNTRIES = {}