# COUNTRY = None

# COUNTRY_CODE = None
# COUNTRY_SLANGS = None

# COUNTRY_LONG = None
# COUNTRY_LAT = None

# COUNTRY_LOCATION_SLANGS = None
# COUNTRY_USER_DESCRIPTION_SLANGS = None

# HASHTAGS_COUNTRY_FILTERS = None

# KNOWN_COUNTRY_TWITTER_USERNAMES = []

# KNOWN_USERNAMES_COUNTRIES = {}

COUNTRY = 'India'

COUNTRY_CODE = 'IN'
COUNTRY_SLANGS = ['India']

COUNTRY_LONG = 77
COUNTRY_LAT = 20

COUNTRY_LOCATION_SLANGS = 'India|india'
COUNTRY_USER_DESCRIPTION_SLANGS = 'India|india'

HASHTAGS_COUNTRY_FILTERS = ['India']

KNOWN_COUNTRY_TWITTER_USERNAMES = []

KNOWN_USERNAMES_COUNTRIES = {}
